operato.wms.parcel.name: wms-parcel
operato.wms.parcel.version: 1.0.0.0
operato.wms.parcel.built.at: 2026-06-16 13:56:14
operato.wms.parcel.projectName: operato-wms-parcel
operato.wms.parcel.description: Operato WMS Parcel Module
operato.wms.parcel.parentModule: wms-base
operato.wms.parcel.basePackage: operato.wms.parcel
operato.wms.parcel.scanEntityPackage: operato.wms.parcel.entity
operato.wms.parcel.scanServicePackage: operato.wms.parcel.rest
