operato.wms.stock.name: wms-stock
operato.wms.stock.version: 1.0.0.0
operato.wms.stock.built.at: 2023-12-12 09:00:00
operato.wms.stock.projectName: operato-wms-stock
operato.wms.stock.description: Operato WMS Stock Module
operato.wms.stock.parentModule: wms-base
operato.wms.stock.basePackage: operato.wms.stock
operato.wms.stock.scanEntityPackage: operato.wms.stock.entity
operato.wms.stock.scanServicePackage: operato.wms.stock.rest