operato.wms.fulfillment.name: wms-fulfillment
operato.wms.fulfillment.version: 1.0.0.0
operato.wms.fulfillment.built.at: 2026-03-26 16:55:00
operato.wms.fulfillment.projectName: operato-wms-fulfillment
operato.wms.fulfillment.description: Operato WMS Fulfillment Module
operato.wms.fulfillment.parentModule: wms-base
operato.wms.fulfillment.basePackage: operato.wms.fulfillment
operato.wms.fulfillment.scanEntityPackage: operato.wms.fulfillment.entity
operato.wms.fulfillment.scanServicePackage: operato.wms.fulfillment.rest
