operato.wms.oms.name: wms-oms
operato.wms.oms.version: 1.0.0.0
operato.wms.oms.built.at: 2026-03-26 16:53:22
operato.wms.oms.projectName: operato-wms-oms
operato.wms.oms.description: Operato WMS Oms Module
operato.wms.oms.parentModule: wms-base
operato.wms.oms.basePackage: operato.wms.oms
operato.wms.oms.scanEntityPackage: operato.wms.oms.entity
operato.wms.oms.scanServicePackage: operato.wms.oms.rest
