operato.wms.outbound.name: wms-outbound
operato.wms.outbound.version: 1.0.0.0
operato.wms.outbound.built.at: 2023-12-12 09:00:00
operato.wms.outbound.projectName: operato-wms-outbound
operato.wms.outbound.description: Operato WMS Outbound Module
operato.wms.outbound.parentModule: wms-base
operato.wms.outbound.basePackage: operato.wms.outbound
operato.wms.outbound.scanEntityPackage: operato.wms.outbound.entity
operato.wms.outbound.scanServicePackage: operato.wms.outbound.rest