operato.wms.vas.name: wms-vas
operato.wms.vas.version: 1.0.0.0
operato.wms.vas.built.at: 2026-03-17 23:30:00
operato.wms.vas.projectName: operato-wms-vas
operato.wms.vas.description: Operato WMS VAS (Value-Added Service) Module
operato.wms.vas.parentModule: wms-base
operato.wms.vas.basePackage: operato.wms.vas
operato.wms.vas.scanEntityPackage: operato.wms.vas.entity
operato.wms.vas.scanServicePackage: operato.wms.vas.rest
