operato.wms.base.name: wms-base
operato.wms.base.version: 1.0.0.0
operato.wms.base.built.at: 2023-12-12 09:00:00
operato.wms.base.projectName: operato-wms-base
operato.wms.base.description: Operato WMS Base Module
operato.wms.base.parentModule: anysys
operato.wms.base.basePackage: operato.wms.base
operato.wms.base.scanEntityPackage: operato.wms.base.entity
operato.wms.base.scanServicePackage: operato.wms.base.rest