operato.wms.name: operato-wms
operato.wms.version: 1.0.0.0
operato.wms.built.at: 2023-12-12 09:00:00
operato.wms.projectName: operato-wms
operato.wms.description: Operato WMS Main Project
operato.wms.parentModule: wms-outbound
operato.wms.basePackage: operato.wms
operato.wms.scanEntityPackage: operato.wms.entity
operato.wms.scanServicePackage: operato.wms.rest