operato.wms.rwa.name: wms-rwa
operato.wms.rwa.version: 1.0.0.0
operato.wms.rwa.built.at: 2026-03-17 23:00:00
operato.wms.rwa.projectName: operato-wms-rwa
operato.wms.rwa.description: Operato WMS RWA (Return Warehouse Authorization) Module
operato.wms.rwa.parentModule: wms-base
operato.wms.rwa.basePackage: operato.wms.rwa
operato.wms.rwa.scanEntityPackage: operato.wms.rwa.entity
operato.wms.rwa.scanServicePackage: operato.wms.rwa.rest
