operato.wms.inbound.name: wms-inbound
operato.wms.inbound.version: 1.0.0.0
operato.wms.inbound.built.at: 2023-12-12 09:00:00
operato.wms.inbound.projectName: operato-wms-inbound
operato.wms.inbound.description: Operato WMS Inbound Module
operato.wms.inbound.parentModule: wms-base
operato.wms.inbound.basePackage: operato.wms.inbound
operato.wms.inbound.scanEntityPackage: operato.wms.inbound.entity
operato.wms.inbound.scanServicePackage: operato.wms.inbound.rest